name: Generate Deploy Preview

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Build documentation
      run: |
        make venv
        make html
        mkdir to-github
        mv build/html to-github/${{ github.sha }}
        touch to-github/.nojekyll
      working-directory: Doc
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.2.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: Doc/to-github
    - name: Comment Deploy Preview Link
      uses: thollander/actions-comment-pull-request@1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: Deploy preview available at https://hugovk.github.io/cpython/${{ github.sha }}
