name: Read the Docs PR preview
on:
  pull_request_target:
    types:
      - opened
    paths:
    - 'Doc/**'
    - 'Misc/**'
    - '.github/workflows/doc.yml'

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: hugovk/actions/preview@netlify
        with:
          project-slug: "hugovk-cpython"
          platform: "netlify"
          single-version: "true"
