name: Mark stale pull requests

on:
  schedule:
  - cron: "0 0 * * *"

permissions:
  pull-requests: write

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        exempt-pr-labels: 'CLA not signed'
        stale-pr-message: 'This PR is stale because it has been open for 30 days with no activity.'
        stale-pr-label: 'stale'
        days-before-stale: 30
        days-before-close: -1

    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-pr-labels: 'CLA not signed'
        stale-pr-message: 'This PR is stale because it has been open for 30 days with no activity. If the CLA is not signed within one week, it will be closed.'
        stale-pr-label: 'stale'
        close-pr-message: 'Closing this stale PR because the CLA is still not signed.'
        days-before-stale: 30
        days-before-close: 7
